apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    node.service: opensearch-data1-dev
  name: opensearch-data1-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
